function GroupedBarChartSkeleton() {
  return (
    <div className="my-3 overflow-x-hidden rounded-md bg-gray-50 py-1 pb-2 shadow-lg dark:bg-dark">
      <div className="my-3 flex min-w-fit justify-between px-1 py-1 md:px-3">
        <div className="h-8 w-14 animate-pulse rounded bg-gray-300 md:w-36"></div>
        <div className="mt-1 flex justify-around md:mr-5">
          <div className="mx-3 mt-2 h-4 w-4 animate-pulse rounded-full bg-gray-300"></div>
          <div className="h-6 w-14 animate-pulse rounded bg-gray-300 md:w-20"></div>
          <div className="mx-3 mt-2 h-4 w-4 animate-pulse rounded-full bg-gray-300"></div>
          <div className="h-6 w-14 animate-pulse rounded bg-gray-300 md:w-20"></div>
        </div>
        <div className="xs:mr-1">
          <div className="lg:w-30 h-8 w-20 animate-pulse rounded bg-gray-300 md:w-20 2xl:w-40"></div>
        </div>
      </div>

      <svg
        className="w-full overflow-x-hidden"
        viewBox="0 0 110 50"
        preserveAspectRatio="xMidYMid meet"
        xmlns="http://www.w3.org/2000/svg"
      >
        <rect
          x="10"
          y="20"
          width="3"
          height="80"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="14"
          y="10"
          width="3"
          height="80"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="20"
          y="40"
          width="3"
          height="70"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="24"
          y="10"
          width="3"
          height="90"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="30"
          y="30"
          width="3"
          height="70"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="34"
          y="40"
          width="3"
          height="70"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="40"
          y="10"
          width="3"
          height="60"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="44"
          y="20"
          width="3"
          height="80"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="50"
          y="10"
          width="3"
          height="50"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="54"
          y="20"
          width="3"
          height="80"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="60"
          y="20"
          width="3"
          height="70"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="64"
          y="40"
          width="3"
          height="20"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="70"
          y="20"
          width="3"
          height="50"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="74"
          y="20"
          width="3"
          height="40"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="80"
          y="20"
          width="3"
          height="70"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="84"
          y="0"
          width="3"
          height="80"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="90"
          y="10"
          width="3"
          height="70"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="94"
          y="20"
          width="3"
          height="80"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="100"
          y="40"
          width="3"
          height="50"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
        <rect
          x="104"
          y="14"
          width="3"
          height="40"
          className="animate-pulse"
          fill="#e5e7eb"
          ry="1.5"
        />
      </svg>
    </div>
  );
}

export default GroupedBarChartSkeleton;
