import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "../Theme/ThemeProvider";
import ExpandProvider from "@/components/ExpandProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="debug-screens">
        <ExpandProvider>
          <Provider>{children}</Provider>
        </ExpandProvider>
      </body>
    </html>
  );
}
